name: example_app
description: A Very Good Project created by Very Good CLI, featuring a counter app with internationalization support and multiple flavors. The counter now increments by 2 with each button press.
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true